manipulator_velocity_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  gains:
    joint_1:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_2:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_3:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_4:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_5:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_6:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
manipulator_effort_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  gains:
    joint_1:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_2:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_3:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_4:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_5:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_6:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
manipulator_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  gains:
    joint_1:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_2:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_3:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_4:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_5:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
    joint_6:
      p: 100
      d: 5
      i: 0.01
      i_clamp: 1
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    goals:
      trajectory: 0.1
  goal_tolerance:
    joint_1: 0.01  # Increase tolerance (in radians)
    joint_2: 0.01  # Increase tolerance (in radians)
    joint_3: 0.01  # Increase tolerance (in radians)
    joint_4: 0.01  # Increase tolerance (in radians)
    joint_5: 0.01  # Increase tolerance (in radians)
    joint_6: 0.01  # Increase tolerance (in radians)
